### ISSUE TITLE
Image + repository deletion fails on the second run

### ISSUE THREAD

**Issue by myllynen** [ansible/galaxy_collection#329]
Deleting content from a private automation hub using:

```
  vars:
    ah_ee_images:
      - name: custom/test
        state: absent
    ah_ee_repositories:
      - name: custom/test
        state: absent
  roles:
    - infra.ah_configuration.ee_image
    - infra.ah_configuration.ee_repository
```

Works once when custom/test exists but fails the next run with "msg: The custom/test repository does not exist" .
