### ISSUE TITLE
ERROR! couldn't resolve module/action 'ah_group_perm'

### ISSUE THREAD

**Issue by demonpig** [ansible/galaxy_collection#441]
## Summary

The `galaxy.galaxy.group` module calls a module (`ah_group_perm`) that was marked as depracated but then removed in the following commit. Because of this, playbook fails with error message regarding a module it can't find.

- https://github.com/ansible/galaxy_collection/pull/435

## Issue Type

- Bug Report

## Ansible, Collection, Private Automation Hub details

```yaml
# requirements.yml
---

collections:
  - name: https://github.com/ansible/galaxy_collection.git
    type: git

  - name: https://github.com/ansible-collections/ansible_hub.git
    type: git
```

```console
# ansible-galaxy collection list
# /root/.ansible/collections/ansible_collections
Collection    Version    
------------- -----------
ansible.hub   1.0.0      
galaxy.galaxy 1.1.1-devel
```

**Note**: The version specified for the `galaxy.galaxy` collection appears to not exist. This is what gets reported when installing the collection using the above `requirements.yml` file.

## OS / ENVIRONMENT

- Red Hat Enterprise Linux 8/9

## Desired Behavior

Collection only uses modules that can be found.

## Actual Behavior

Receiving the following error message when executing a playbook that makes use of the `galaxy.galaxy.group` role.

```console (error)
TASK [Include group role] *********************************************************************************************************************
task path: /home/username/playbook.yml:224
redirecting (type: modules) galaxy.galaxy.ah_group to ansible.hub.ah_group
[DEPRECATION WARNING]: galaxy.galaxy.ah_group_perm has been deprecated. The endpoint has been removed and is not supported in AAP 2.3 onwards.
This feature will be removed from galaxy.galaxy in version 3.0.0. Deprecation warnings can be disabled by setting deprecation_warnings=False
in ansible.cfg.
ERROR! couldn't resolve module/action 'ah_group_perm'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/home/username/collections/ansible_collections/galaxy/galaxy/roles/group/tasks/main.yml': line 41, column 3, but may
be elsewhere in the file depending on the exact syntax problem.
```

## STEPS TO REPRODUCE

- Install the collections using a `requirements.yml` file (see above)

- Run the following playbook

  ```
  - name: Example Playbook
    hosts: all
    gather_facts: false

    collections:
      - galaxy.galaxy

    tasks:
      - name: Include group role
        ansible.builtin.include_role:
          name: ah_group
  ```
